#!/bin/sh
set -eu

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

echo "Running pre-commit checks..."
make check
#if make check; then
#    echo "Recompiling assets after successful checks..."
#    make cc
#fi
