<?php

declare(strict_types=1);

const SAMPLE_BESTIARY_SLUGS = [
    'aarakocra',
    'aboleth',
    'acolyte',
    'aigle',
    'gobelin',
    'tarasque',
];

$sourcePath = $argv[1] ?? __DIR__ . '/monsters-source.html';
$outputPath = $argv[2] ?? dirname(__DIR__, 2) . '/assets/scripts/lab/dnd/bestiary.js';
$sampleOutputPath = $argv[3] ?? dirname(__DIR__, 2) . '/tests/fixtures/dnd/bestiary-sample.js';

if (!is_file($sourcePath)) {
    fwrite(STDERR, "Fichier source introuvable : {$sourcePath}\n");
    exit(1);
}

$html = file_get_contents($sourcePath);

if ($html === false) {
    fwrite(STDERR, "Impossible de lire le fichier source : {$sourcePath}\n");
    exit(1);
}

$dom = new DOMDocument();
libxml_use_internal_errors(true);
$dom->loadHTML('<?xml encoding="UTF-8">' . $html);
libxml_clear_errors();

$xpath = new DOMXPath($dom);
$blocks = $xpath->query("//div[contains(concat(' ', normalize-space(@class), ' '), ' bloc ')]");

if ($blocks === false) {
    fwrite(STDERR, "Impossible de trouver les blocs de monstres dans {$sourcePath}\n");
    exit(1);
}

$monsters = [];

foreach ($blocks as $index => $block) {
    $nameNode = $xpath->query(".//h1", $block)->item(0);
    $typeNode = $xpath->query(".//div[contains(concat(' ', normalize-space(@class), ' '), ' type ')]", $block)->item(0);
    $redNode = $xpath->query(".//div[contains(concat(' ', normalize-space(@class), ' '), ' red ')]", $block)->item(0);

    if (!$nameNode || !$typeNode || !$redNode) {
        continue;
    }

    $name = trim($nameNode->textContent);
    $typeLine = trim($typeNode->textContent);
    $redText = normalizeText($redNode->textContent);

    $typeData = parseTypeLine($typeLine);
    $armorClass = extractIntAfterLabel($redText, 'Classe d\'armure');
    $hitPoints = extractIntAfterLabel($redText, 'Points de vie');
    $speed = extractTextBetweenLabels($redText, 'Vitesse', ['FOR']);
    $abilities = parseAbilities($xpath, $block);
    $challengeRating = extractChallengeRating($redText);

    $monsters[] = [
        'id' => $index + 1,
        'slug' => slugify($name),
        'name' => $name,
        'challenge_rating' => $challengeRating,
        'type' => $typeData['type'],
        'size' => $typeData['size'],
        'armor_class' => $armorClass,
        'hit_points' => $hitPoints,
        'speed' => $speed,
        'alignment' => $typeData['alignment'],
        'is_legendary' => hasLegendaryActions($xpath, $block),
        'abilities' => $abilities,
        'initiative_modifier' => $abilities['dex']['modifier'] ?? 0,
    ];
}

$json = json_encode(
    $monsters,
    JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
);

if ($json === false) {
    fwrite(STDERR, 'Erreur JSON : ' . json_last_error_msg() . "\n");
    exit(1);
}

$js = <<<JS
// Generated by tools/dnd/complete_monster_extractor.php from tools/dnd/monsters-source.html.
// Do not edit manually.

// noinspection JSAnnotator
export const bestiary = {$json};

JS;

writeFile($outputPath, $js);

$sampleMonsters = selectSampleMonsters($monsters);
$sampleJson = json_encode(
    $sampleMonsters,
    JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
);

if ($sampleJson === false) {
    fwrite(STDERR, 'Erreur JSON fixture : ' . json_last_error_msg() . "\n");
    exit(1);
}

$sampleJs = <<<JS
// Generated by tools/dnd/complete_monster_extractor.php from tools/dnd/monsters-source.html.
// Do not edit manually.

// noinspection JSAnnotator
export const bestiarySample = {$sampleJson};

JS;

writeFile($sampleOutputPath, $sampleJs);

echo count($monsters) . " monstres exportés dans {$outputPath}\n";
echo count($sampleMonsters) . " monstres de test exportés dans {$sampleOutputPath}\n";

function writeFile(string $path, string $content): void
{
    $directory = dirname($path);

    if (!is_dir($directory) && !mkdir($directory, 0775, true) && !is_dir($directory)) {
        fwrite(STDERR, "Impossible de créer le dossier de sortie : {$directory}\n");
        exit(1);
    }

    if (file_put_contents($path, $content) === false) {
        fwrite(STDERR, "Impossible d'écrire le fichier de sortie : {$path}\n");
        exit(1);
    }
}

function selectSampleMonsters(array $monsters): array
{
    $monstersBySlug = array_column($monsters, null, 'slug');
    $sample = [];

    foreach (SAMPLE_BESTIARY_SLUGS as $slug) {
        if (!isset($monstersBySlug[$slug])) {
            fwrite(STDERR, "Monstre de test introuvable dans le bestiaire : {$slug}\n");
            exit(1);
        }

        $sample[] = $monstersBySlug[$slug];
    }

    return $sample;
}

function normalizeText(string $text): string
{
    $text = html_entity_decode($text, ENT_QUOTES | ENT_HTML5, 'UTF-8');
    $text = preg_replace('/\s+/', ' ', $text);

    return trim($text ?? '');
}

function parseTypeLine(string $line): array
{
    $line = normalizeText($line);

    if (preg_match('/^(.*?) de taille ([A-Za-z]+), (.+)$/u', $line, $matches)) {
        return [
            'type' => trim($matches[1]),
            'size' => trim($matches[2]),
            'alignment' => trim($matches[3]),
        ];
    }

    return [
        'type' => $line,
        'size' => null,
        'alignment' => null,
    ];
}

function extractIntAfterLabel(string $text, string $label): ?int
{
    $pattern = '/' . preg_quote($label, '/') . '\s+(\d+)/u';

    if (preg_match($pattern, $text, $matches)) {
        return (int) $matches[1];
    }

    return null;
}

function extractTextBetweenLabels(string $text, string $startLabel, array $endLabels): ?string
{
    $start = mb_strpos($text, $startLabel);

    if ($start === false) {
        return null;
    }

    $start += mb_strlen($startLabel);
    $endPositions = [];

    foreach ($endLabels as $endLabel) {
        $pos = mb_strpos($text, $endLabel, $start);

        if ($pos !== false) {
            $endPositions[] = $pos;
        }
    }

    $end = $endPositions ? min($endPositions) : mb_strlen($text);

    return trim(mb_substr($text, $start, $end - $start));
}

function parseAbilities(DOMXPath $xpath, DOMNode $block): array
{
    $map = [
        'FOR' => 'str',
        'DEX' => 'dex',
        'CON' => 'con',
        'INT' => 'int',
        'SAG' => 'wis',
        'CHA' => 'cha',
    ];

    $abilities = [];
    $caracNodes = $xpath->query(
        ".//div[contains(concat(' ', normalize-space(@class), ' '), ' carac ')]",
        $block
    );

    foreach ($caracNodes as $caracNode) {
        $labelNode = $xpath->query(".//strong", $caracNode)->item(0);

        if (!$labelNode) {
            continue;
        }

        $label = trim($labelNode->textContent);
        $text = normalizeText($caracNode->textContent);

        if (!isset($map[$label])) {
            continue;
        }

        if (preg_match('/(\d+)\s*\(([+-]\d+)\)/u', $text, $matches)) {
            $abilities[$map[$label]] = [
                'score' => (int) $matches[1],
                'modifier' => (int) $matches[2],
            ];
        }
    }

    return $abilities;
}

function hasLegendaryActions(DOMXPath $xpath, DOMNode $block): bool
{
    $rubNodes = $xpath->query(
        ".//div[contains(concat(' ', normalize-space(@class), ' '), ' rub ')]",
        $block
    );

    foreach ($rubNodes as $rubNode) {
        if (normalizeText($rubNode->textContent) === 'Actions légendaires') {
            return true;
        }
    }

    return false;
}

function extractChallengeRating(string $text): ?string
{
    if (preg_match('/Puissance\s+([0-9\/]+)/u', $text, $matches)) {
        return $matches[1];
    }

    return null;
}

function slugify(string $text): string
{
    $text = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $text);
    $text = strtolower($text);
    $text = preg_replace('/[^a-z0-9]+/', '-', $text);

    return trim($text ?? '', '-');
}
