// Generated by tools/dnd/complete_monster_extractor.php from tools/dnd/monsters-source.html.
// Do not edit manually.

// noinspection JSAnnotator
export const bestiarySample = [
    {
        "id": 1,
        "slug": "aarakocra",
        "name": "Aarakocra",
        "challenge_rating": "1/4",
        "type": "Humanoïde (aarakocra)",
        "size": "M",
        "armor_class": 12,
        "hit_points": 13,
        "speed": "6 m, vol 15 m",
        "alignment": "neutre bon",
        "is_legendary": false,
        "abilities": {
            "str": {
                "score": 10,
                "modifier": 0
            },
            "dex": {
                "score": 14,
                "modifier": 2
            },
            "con": {
                "score": 10,
                "modifier": 0
            },
            "int": {
                "score": 11,
                "modifier": 0
            },
            "wis": {
                "score": 12,
                "modifier": 1
            },
            "cha": {
                "score": 11,
                "modifier": 0
            }
        },
        "initiative_modifier": 2
    },
    {
        "id": 2,
        "slug": "aboleth",
        "name": "Aboleth",
        "challenge_rating": "10",
        "type": "Aberration",
        "size": "G",
        "armor_class": 17,
        "hit_points": 135,
        "speed": "3 m, nage 12 m",
        "alignment": "loyal mauvais",
        "is_legendary": true,
        "abilities": {
            "str": {
                "score": 21,
                "modifier": 5
            },
            "dex": {
                "score": 9,
                "modifier": -1
            },
            "con": {
                "score": 15,
                "modifier": 2
            },
            "int": {
                "score": 18,
                "modifier": 4
            },
            "wis": {
                "score": 15,
                "modifier": 2
            },
            "cha": {
                "score": 18,
                "modifier": 4
            }
        },
        "initiative_modifier": -1
    },
    {
        "id": 3,
        "slug": "acolyte",
        "name": "Acolyte",
        "challenge_rating": "1/4",
        "type": "Humanoïde (toute race)",
        "size": "M",
        "armor_class": 10,
        "hit_points": 9,
        "speed": "9 m",
        "alignment": "tout alignement",
        "is_legendary": false,
        "abilities": {
            "str": {
                "score": 10,
                "modifier": 0
            },
            "dex": {
                "score": 10,
                "modifier": 0
            },
            "con": {
                "score": 10,
                "modifier": 0
            },
            "int": {
                "score": 10,
                "modifier": 0
            },
            "wis": {
                "score": 14,
                "modifier": 2
            },
            "cha": {
                "score": 11,
                "modifier": 0
            }
        },
        "initiative_modifier": 0
    },
    {
        "id": 4,
        "slug": "aigle",
        "name": "Aigle",
        "challenge_rating": "0",
        "type": "Bête",
        "size": "P",
        "armor_class": 12,
        "hit_points": 3,
        "speed": "3 m, vol 18 m",
        "alignment": "sans alignement",
        "is_legendary": false,
        "abilities": {
            "str": {
                "score": 6,
                "modifier": -2
            },
            "dex": {
                "score": 15,
                "modifier": 2
            },
            "con": {
                "score": 10,
                "modifier": 0
            },
            "int": {
                "score": 2,
                "modifier": -4
            },
            "wis": {
                "score": 14,
                "modifier": 2
            },
            "cha": {
                "score": 7,
                "modifier": -2
            }
        },
        "initiative_modifier": 2
    },
    {
        "id": 200,
        "slug": "gobelin",
        "name": "Gobelin",
        "challenge_rating": "1/4",
        "type": "Humanoïde (gobelinoïde)",
        "size": "P",
        "armor_class": 15,
        "hit_points": 7,
        "speed": "9 m",
        "alignment": "neutre mauvais",
        "is_legendary": false,
        "abilities": {
            "str": {
                "score": 8,
                "modifier": -1
            },
            "dex": {
                "score": 14,
                "modifier": 2
            },
            "con": {
                "score": 10,
                "modifier": 0
            },
            "int": {
                "score": 10,
                "modifier": 0
            },
            "wis": {
                "score": 8,
                "modifier": -1
            },
            "cha": {
                "score": 8,
                "modifier": -1
            }
        },
        "initiative_modifier": 2
    },
    {
        "id": 393,
        "slug": "tarasque",
        "name": "Tarasque",
        "challenge_rating": "30",
        "type": "Monstruosité (titan)",
        "size": "Gig",
        "armor_class": 25,
        "hit_points": 676,
        "speed": "12 m",
        "alignment": "sans alignement",
        "is_legendary": true,
        "abilities": {
            "str": {
                "score": 30,
                "modifier": 10
            },
            "dex": {
                "score": 11,
                "modifier": 0
            },
            "con": {
                "score": 30,
                "modifier": 10
            },
            "int": {
                "score": 3,
                "modifier": -4
            },
            "wis": {
                "score": 11,
                "modifier": 0
            },
            "cha": {
                "score": 11,
                "modifier": 0
            }
        },
        "initiative_modifier": 0
    }
];
