# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session:
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax
        cookie_lifetime: 0
        gc_maxlifetime: 43200

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
